//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "article")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub article_id: Uuid,
    pub user_id: Uuid,
    #[sea_orm(column_type = "Text", unique)]
    pub slug: String,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    #[sea_orm(column_type = "Text")]
    pub body: String,
    #[sea_orm(column_type = "Custom(\"array\".to_owned())")]
    pub tag_list: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
    belongs_to = "super::user::Entity",
    from = "Column::UserId",
    to = "super::user::Column::UserId",
    on_update = "NoAction",
    on_delete = "Cascade"
    )]
    User,
    #[sea_orm(has_many = "super::article_favorite::Entity")]
    ArticleFavorite,
    #[sea_orm(has_many = "super::article_comment::Entity")]
    ArticleComment,
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl Related<super::article_favorite::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArticleFavorite.def()
    }
}

impl Related<super::article_comment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArticleComment.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
