//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "follow")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub followed_user_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub following_user_id: Uuid,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
    belongs_to = "super::user::Entity",
    from = "Column::FollowedUserId",
    to = "super::user::Column::UserId",
    on_update = "NoAction",
    on_delete = "Cascade"
    )]
    User2,
    #[sea_orm(
    belongs_to = "super::user::Entity",
    from = "Column::FollowingUserId",
    to = "super::user::Column::UserId",
    on_update = "NoAction",
    on_delete = "Cascade"
    )]
    User1,
}

impl ActiveModelBehavior for ActiveModel {}
