//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

pub use super::article::Entity as Article;
pub use super::article_comment::Entity as ArticleComment;
pub use super::article_favorite::Entity as ArticleFavorite;
pub use super::follow::Entity as Follow;
pub use super::user::Entity as User;

